version: "3"
services:
  nginx_balancer:
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/balancer.conf:/etc/nginx/conf.d/balancer.conf
  nginx_1:
    image: nginx:stable
    ports:
      - "8001:80"
    volumes:
      - ./html/node1.html:/usr/share/nginx/html/index.html
  nginx_2:
    image: nginx:stable
    ports:
      - "8002:80"
    volumes:
      - ./html/node2.html:/usr/share/nginx/html/index.html
