version: "3"
services:
  master1:
    restart: always
    image: mysql:5.7
    ports:
      - "9001:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_replication
    volumes:
      - ./conf/master.cnf:/etc/mysql/mysql.conf.d/master.cnf
  slave1:
    restart: always
    image: mysql:5.7
    ports:
      - "9011:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_replication
    volumes:
      - ./conf/slave1.cnf:/etc/mysql/mysql.conf.d/slave1.cnf
  slave2:
    restart: always
    image: mysql:5.7
    ports:
      - "9012:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_replication
    volumes:
      - ./conf/slave2.cnf:/etc/mysql/mysql.conf.d/slave2.cnf
